apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sensitive-data
  region: ap-southeast-1

fargateProfiles:
  - name: profile
    selectors:
      - namespace: default
      - namespace: kube-system

secretsEncryption:
  keyARN: arn:aws:kms:ap-southeast-1:<account>:alias/sensitive-data

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: external-secrets-kubernetes-external-secrets
      namespace: kube-system
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"