apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-secrets-manager
spec:
  backendType: secretsManager
  region: ap-southeast-1
  data:
    - key: SensitiveData
      name: value
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-parameter-store
spec:
  backendType: systemManager
  region: ap-southeast-1
  data:
    - key: SensitiveData
      name: value